name: docs_pages_workflow
 
# execute this workflow automatically when we push to main
on:
  push:
    branches: [ main ]
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
 
    steps:
 
    - name: Prereqs
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone --depth 1 "https://token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        chmod +x docs/buildDocs.sh
      shell: bash
 
    - name: Execute script to build our documentation and update pages
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: "docs/buildDocs.sh"
      shell: bash